development:
  sessions:
    default:
      uri: mongodb://localhost:27017/kaleidoscope_dev
test:
  sessions:
    default:
      uri: mongodb://localhost:27017/test
ci:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
