#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'rvm',
         :git => 'https://github.com/fnichol/chef-rvm'
cookbook 'git'
cookbook 'mongodb'
cookbook 'zsh'
cookbook 'oh-my-zsh',
         :git => 'https://github.com/satyamag/chef-oh-my-zsh.git'
cookbook 'libcurl',
         :git => 'https://github.com/ashwinwhat/libcurl.git'


